title: Messages
modelClass: NielsVanDenDries\Messenger\Models\Messages
list: $/nielsvandendries/messenger/models/messages/columns.yaml
recordUrl: 'nielsvandendries/messenger/messages/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
